title: Your awesome title #  !!! nome del sito !!! PERSONALIZZARE !!!
email: your-email@example.com #  email ufficiale di contatto !!! PERSONALIZZARE !!!
description: >- # descrizione del sito  !!! PERSONALIZZARE !!!
  Sito ufficiale di questa associazione.
baseurl: "/"  #  !!! non toccare !!!
url: "https://so.dipartimento.polo18f.it" # URL del sito (cambiare)

# Build settings
theme: minima #  !!! non toccare !!!
plugins: #  !!! non toccare !!!
  - jekyll-feed #  !!! non toccare !!! 

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
