title: Associazione di esempio #  !!! nome del sito !!! PERSONALIZZARE !!!
email: info@18f.it #  email ufficiale di contatto !!! PERSONALIZZARE !!!
description: >- # descrizione del sito  !!! PERSONALIZZARE !!!
  Template di "associazioni" realizzato con bootstrap italia 5.0.
baseurl: "/design-associazione-it/"  #  !!! non toccare !!!
url: "https://so.dipartimento.polo18f.it" # URL del sito (cambiare)

# Build settings
theme: minima #  !!! non toccare !!!
plugins: #  !!! non toccare !!!
  - jekyll-feed #  !!! non toccare !!! 

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
