backend:
  name: git-gateway
  branch: master   # cambia se usi master o altro branch

media_folder: "images"
public_folder: "/images"

site_url: ""
logo_url: "/images/logo.png" # opzionale

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Contenuto", name: "body", widget: "markdown" }
